version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins_container
    user: jenkins
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "./data/jenkins"
    labels:
      - "traefik.docker.networks=traffic"
      - "traefik.frontend.rule=Host:${DOMAIN}.${BASE_URL}"
      - "traefik.port=8080"
    networks:
      traffic:
networks:
  traffic:
    external: true
