version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: "jenkins_container"
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traffic"
      - "traefik.frontend.rule=Host:${DOMAIN}.${BASE_URL}"
      - "traefik.port=8080"
    networks:
      - traffic
networks:
  traffic:
    external: true
